### ISSUE TITLE
运行初始化数据库 提示 找不到livecode这个包。

### ISSUE THREAD

**Issue by yanwen** [mikuh/livecode#3]
弱弱问一下。是不是init_db.py文件里写错了？？？

`sys.path.extend(['../live_code'])   `

**Comment by mikuh** [comment]
改成这样 sys.path.extend(['../../live_code'])

**Comment by yanwen** [comment]
。。没有这个路径的文件夹  live_code 
我改成这样：
`sys.path.append('../')`
跑起来了。但是其他地方还是会报错。。

如果有空的话 可以看一下不？？感谢。😆😁

**Comment by yanwen** [comment]
改成`sys.path.extend(['../'])`这样之后
报错了。

`Traceback (most recent call last):
  File "/Users/yw/Downloads/livecode-master/livecode/init/init_db.py", line 10, in <module>
    configs = load_config('../configs/base.yaml')
  File "../livecode/utils.py", line 23, in load_config
    with open(path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../configs/base.yaml'`
